export const ADD_AUDIO = 'ADD_AUDIO';
export const RENAME_AUDIO = 'RENAME_AUDIO';
export const DELETE_AUDIO = 'DELETE_AUDIO';
export const FETCH_AUDIO = 'FETCH_AUDIO';
export const TOGGLE_BOOKMARK_AUDIO = 'TOGGLE_BOOKMARK_AUDIO';